call sign "..\Installs\EZTech Vision Emulators 26b01A6.exe" 
call sign "..\Installs\EZTech Vision 26b01A6.exe" 
call sign "..\Installs\EZForecourt Plus 26b01A6.exe" 
call sign "..\Installs\EZForecourt USB 26b01A6.exe" 
call sign "..\Installs\EZForecourt Client 26b01A6.exe" 
call sign "..\Installs\EZForecourt Plus Emulators 26b01A6.exe" 
call sign "..\Installs\EZForecourt USB Emulators 26b01A6.exe" 
call sign "..\Installs\EZTag 26b01A6.exe" 