call sign "..\Installs\EZTech Vision Emulators 25b12B1.exe" 
call sign "..\Installs\EZTech Vision 25b12B1.exe" 
call sign "..\Installs\EZForecourt Plus 25b12B1.exe" 
call sign "..\Installs\EZForecourt USB 25b12B1.exe" 
call sign "..\Installs\EZForecourt Client 25b12B1.exe" 
call sign "..\Installs\EZForecourt Plus Emulators 25b12B1.exe" 
call sign "..\Installs\EZForecourt USB Emulators 25b12B1.exe" 
call sign "..\Installs\EZTag 25b12B1.exe" 